
<br/>
<div class="row">
    <div class="span6">
        <div class="well">
            <h1>Brand info</h1>
            <div><?= $this->brandForm; ?></div>
        </div>
    </div>
    <div class="span6">
        <div class="well">
            <h1>Owner info</h1>
            <div><?= $this->ownerForm; ?></div>
        </div>
    </div>
</div>

<!--<div class="row brand-actions">-->
<!--    <div class="span12">-->
<!--        <button>Combine</button>-->
<!--    </div>-->
<!--</div>-->

