<table>
    <tr>
        <td><b>Р/р</b></td>
        <td>29244799265001</td>
    </tr>
    <tr>
        <td><b>МФО</b></td>
        <td>356282</td>
    </tr>
    <tr>
        <td><b>ОКПО</b></td>
        <td>14360570</td>
    </tr>
    <tr>
        <td><b>Сума</b></td>
        <td><?= $this->amount ?>&nbsp;грн.</td>
    </tr>
    <tr>
        <td><b>Призначення</b></td>
        <td><?= $this->description ?></td>
    </tr>
</table>