<? global $translate; ?>
<? if ($this->error) : ?>
    <div>
        <h2>Error</h2>
        <div><?= $this->errorMsg ?></div>
    </div>
<? endif ?>

<div class="orderDetails">
    <div class="row"><label><?= $translate->getAdapter()->translate("name") ?></label><div><?= $this->order->ad->name ?></div></div>
    <div class="row"><label><?= $translate->getAdapter()->translate("price") ?></label><div><?= $this->order->amount ?></div></div>
    <div class="row"><label><?= $translate->getAdapter()->translate("days_count") ?></label><div><?= $this->order->ad->getDaysCount() ?></div></div>
    <div class="row"><label><?= $translate->getAdapter()->translate("public_date") ?></label><div><?= $this->order->ad->public_dt ?></div></div>
    <div class="row"><label><?= $translate->getAdapter()->translate("end_date") ?></label><div><?= $this->order->ad->end_dt ?></div></div>
</div>

<form action="https://www.liqpay.com/?do=clickNbuy" method="POST" />
    <input type="hidden" name="operation_xml" value="<?= $this->xml ?>" />
    <input type="hidden" name="signature" value="<?= $this->signature ?>" />
    <input type="submit" value="<?= $translate->getAdapter()->translate("continue_payment")?>">
    <input type="button" value="<?= $translate->getAdapter()->translate("cancel")?>">
</form>