<?php global $translate; ?>
<?php if ($this->error) : ?>
    <div>
        <h2>Error</h2>
        <div><?= $this->errorMsg ?></div>
    </div>
<?php endif ?>
    
<div class="orderDetails">    
    <h5><?= $translate->getAdapter()->translate("payment_details") ?></h5>
    <table class="table table-bordered table-striped">
      <tbody>
        <tr>
          <td><?= $translate->getAdapter()->translate("name") ?></td>
          <td><?= $this->order->ad->name ?></td>
        </tr>
        <tr>
          <td><?= $translate->getAdapter()->translate("amount") ?></td>
          <td><?= $this->order->amount ?></td>
        </tr>
        <tr>
          <td><?= $translate->getAdapter()->translate("days_count") ?></td>
          <td><?= $this->order->ad->getDaysCount() ?></td>
        </tr>
        <tr>
          <td><?= $translate->getAdapter()->translate("public_date") ?></td>
          <td><?= $this->order->ad->public_dt ?></td>
        </tr>
        <tr>
          <td><?= $translate->getAdapter()->translate("end_date") ?></td>
          <td><?= $this->order->ad->end_dt ?></td>
        </tr>
      </tbody>
    </table>
</div>

<?php if (0) { ?>
<form action="https://www.liqpay.com/?do=clickNbuy" method="POST" />
    <input type="hidden" name="operation_xml" value="<?= $this->xml ?>" />
    <input type="hidden" name="signature" value="<?= $this->signature ?>" />
    <input type="submit" value="<?= $translate->getAdapter()->translate("continue_payment")?>">
    <a href="/payment/cancel/id/<?= $this->order->id ?>"><input type="button" value="<?= $translate->getAdapter()->translate("cancel")?>"></a>
</form>

<form action="/payment/invoice" method="post">
    <?php foreach($this->orderData as $key => $val) { ?>
        <input type="hidden" value="<?= $val ?>" name="<?= $key ?>"/>
    <?php } ?>
    <input type="submit" value="<?= $translate->getAdapter()->translate("invoice") ?>"/>
</form>
<?php } ?>
<a href="/payment/finish/order_id/<?= $this->order->id ?>"><input type="button" value="<?= $translate->getAdapter()->translate("publish")?>"></a>
<a href="/payment/cancel/id/<?= $this->order->id ?>"><input type="button" value="<?= $translate->getAdapter()->translate("cancel")?>"></a>