<?php global $translate; ?>
<div class="row contacts">
    <div class="span5 offset2">

        <address>
            <strong><?= $translate->getAdapter()->translate("contact_org_name")?></strong><br>
            <br>
            <!--  &nbsp;&nbsp;<?//= $translate->getAdapter()->translate("contact_org_skype_name")?><?//= $translate->getAdapter()->translate("contact_org_skype_val")?><br> -->
            <i class="cicon-mail"></i><a href="mailto:<?= $translate->getAdapter()->translate("contact_org_email")?>">
                <?= $translate->getAdapter()->translate("contact_org_email")?>
            </a><br>
            <i class="cicon-phone"></i><?= $translate->getAdapter()->translate("contact_org_phone_name")?><?= $translate->getAdapter()->translate("contact_org_phone_val")?> <br>
            <i class="cicon-phone"></i><?= $translate->getAdapter()->translate("contact_org_phone_name")?><?= $translate->getAdapter()->translate("contact_org_phone_val2")?> <br>
            <a href='http://vk.com/saleoninfo' target="_blank"><div class="vk"></div></a> <a href='https://www.facebook.com/saleoninfo' target="_blank"><div class="fb"></div></a><a href="https://twitter.com/saleoninfo" target="_blank"><div class="twitter"></div></a><a href="https://www.youtube.com/watch?v=qRBjaq9XRlo" target="_blank"><div class="youtube"></div></a><br>
            <a href='http://saleon.info' style="display:block; margin-left: 25px; margin-top:45px;">© SALEON 2014 - <script>var year = new Date(); document.write(year.getFullYear());</script></a><br>
        </address>

    </div>
    <div class="span5" style="border: none !important;">
        <?php echo $this->form; ?>


    </div>

</div>




