<?php global $translate; ?>
<div class="row contacts">
    <div class="span5 offset2">

        <address>
            <strong><?= $translate->getAdapter()->translate("contact_org_name")?></strong><br>
            <i class="cicon-phone"></i><?= $translate->getAdapter()->translate("contact_org_phone_name")?><?= $translate->getAdapter()->translate("contact_org_phone_val")?> <br>
            <i class="cicon-mail"></i><a href="mailto:<?= $translate->getAdapter()->translate("contact_org_email")?>">
                    <?= $translate->getAdapter()->translate("contact_org_email")?>
                </a><br>
            <i class="icon-globe"></i>
                &nbsp;&nbsp;<?= $translate->getAdapter()->translate("contact_org_skype_name")?><?= $translate->getAdapter()->translate("contact_org_skype_val")?>
        </address>

    </div>
    <div class="span5">
        <strong><?= $translate->getAdapter()->translate("contact_org_share_link")?></strong>
        <br>

        <script type="text/javascript">(function() {
          if (window.pluso)if (typeof window.pluso.start == "function") return;
          if (window.ifpluso==undefined) { window.ifpluso = 1;
            var d = document, s = d.createElement('script'), g = 'getElementsByTagName';
            s.type = 'text/javascript'; s.charset='UTF-8'; s.async = true;
            s.src = ('https:' == window.location.protocol ? 'https' : 'http')  + '://share.pluso.ru/pluso-like.js';
            var h=d[g]('body')[0];
            h.appendChild(s);
          }})();
        </script>
        <div class="pluso" data-background="transparent" 
        data-options="big,square,line,horizontal,nocounter,theme=08" data-services="vkontakte,odnoklassniki,facebook,twitter,google,moimir,email"></div>

    </div>
    
</div>




