<?php global $translate; ?>
<div id="main-page-slider" class="row-fluid">
	<div id="myCarousel" class="carousel slide hide">
		<div class="carousel-inner">
			<div class="item active">
				<div class="items-wrapper">
					<div class="row-fluid">
						<?php
						    foreach ($this->items as $item) {
						        echo $this->adItem($item);
						    }
						?>		
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="modal hide fade subscription-form-modal">
    <div><span class="modal-close-btn" data-dismiss="modal">&times;</span></div>
    <div>
        <?= $this->subscriptionForm; ?>
    </div>
    <div><a href="/subscription/manager"><?php echo $translate->getAdapter()->translate("subscription_settings"); ?> >></a></div>
</div>

<script type="text/javascript">
    <?php 
    	echo "window.requestUrl  = \"/ad/list\";";
    	echo "window.pageName 	 = \"mainPage\";";
    ?>
</script>
