<?php global $translate; ?>
<?php $this->headTitle($translate->getAdapter()->translate("enter")); ?>
<div class="col-xs-12 col-sm-4 col-sm-offset-4">
    <div class="page-header">
        <h2>
            <?php echo $translate->getAdapter()->translate("enter"); ?>
        </h2>
    </div>
    <?php if ($this->errorStatus) { ?>
        <div class="alert alert-error"><h4>
            <?php echo $translate->getAdapter()->translate("error"); ?>!</h4>&nbsp;<?php echo $translate->getAdapter()->translate("wrong_email_or_password"); ?>
        </div>
    <?php } ?>
</div>