<?php global $translate; ?>
<?php //$this->headTitle($translate->getAdapter()->translate("enter")."/"); ?>
<div class="col-sm-12 col-sm-4 col-sm-offset-4">
    <h3><?php echo $translate->getAdapter()->translate("enter"); ?></h3>
    <?php if ($this->errorStatus) { ?>
        <div class="alert alert-danger">
            <h4>
                <?php echo $translate->getAdapter()->translate("error"); ?>!
            </h4>
            <?php echo $translate->getAdapter()->translate("wrong_email_or_password"); ?>
        </div>
    <?php } ?>
    <?php echo $this->form->setAction($this->url()); ?>
</div>