<?php global $translate; ?>
<div id="main-page-slider" class="row-fluid"></div>

<script type="text/javascript">
    window.messages = {};
    <?php 
        echo "window.messages.noFavoritesData  = \"" . $translate->getAdapter()->translate("no_favorites_data_available") . "\";";
        echo "window.requestUrl  = \"/ad/favorites\";";
        echo "window.pageName    = \"favoritesPage\";";
    ?>
</script>