
<script type="text/javascript">
    (function() {
        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
        po.src = 'https://apis.google.com/js/client:plusone.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
    })();
</script>


    <script type="text/javascript">
        function GLogin(authResult) {
            if (authResult['code']) {

                // Скрыть кнопку входа после авторизации пользователя, например:
                $('#signinButton').attr('style', 'display: none');

                // Отправляет код на сервер
                $.ajax({
                    type: 'POST',
                    url: '/test/auth?storeToken',
                    contentType: 'application/octet-stream; charset=utf-8',
                    success: function(result) {
                        // Обрабатывает или проверяет ответ сервера при необходимости.

                        // Печатает список предоставляемых пользователем контактов
                        // в консоли.
                        console.log(result);
                        if (result['profile'] && result['people']){
                            $('#results').html('Hello ' + result['profile']['displayName'] + '. You successfully made a server side call to people.get and people.list');
                        } else {
                            $('#results').html('Failed to make a server-side call. Check your configuration and console.');
                        }
                    },
                    processData: false,
                    data: authResult['code']
                });
            } else if (authResult['error']) {
                // Произошла ошибка.
                // Возможные коды ошибок:
                //   "access_denied" – пользователь отказался предоставить приложению доступ к данным
                //   "immediate_failed" – не удалось выполнить автоматический вход пользователя
                console.log('There was an error: ' + authResult['error']);
            }
        }
</script>

<div id="signinButton">
  <span class="g-signin"
        data-scope="https://www.googleapis.com/auth/plus.login"
        data-clientid="897869651508-gfk2vv17r495ructelva10aav8qoblh7.apps.googleusercontent.com"
        data-redirecturi="postmessage"
        data-accesstype="offline"
        data-cookiepolicy="single_host_origin"
        data-callback="GLogin">
  </span>
</div>
<div id="result"></div>