<div id="main-page-slider" class="row-fluid">
	<div id="myCarousel" class="carousel slide hide">
		<div class="carousel-inner">
			<div class="item active">
				<div class="items-wrapper">
					<div class="row-fluid">
						<?php
						    foreach ($this->items as $item) {
						        echo $this->adItem($item);
						    }
						?>		
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
    <?php 
    	echo "window.requestUrl  = \"/ad/list\";";
    	echo "window.pageName 	 = \"mainPage\";";
    ?>
</script>
