<?php global $translate; ?>
<br />
<div id="view-content">
    <ul class="nav nav-tabs" id="ad">
        <li class="active"><a href="#main"><?php echo $translate->getAdapter()->translate("main"); ?></a></li>
        <li><a href="#dates"><?php echo $translate->getAdapter()->translate("dates"); ?></a></li>
        <li><a href="#settings"><?php echo $translate->getAdapter()->translate("settings"); ?></a></li>
        <li><a href="#contacts"><?php echo $translate->getAdapter()->translate("contacts"); ?></a></li>
        <li><a href="#media"><?php echo $translate->getAdapter()->translate("media"); ?></a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="main"><?php echo $this->mainForm->setAction($this->url()); ?></div>
        <div class="tab-pane" id="dates"><?php echo $this->datesForm->setAction($this->url()); ?></div>
        <div class="tab-pane" id="settings"><?php echo $this->settingsForm->setAction($this->url()); ?></div>
        <div class="tab-pane" id="contacts"><?php echo $this->contactsForm->setAction($this->url()); ?></div>
        <div class="tab-pane" id="media">
            <div class="span5"><?php echo $this->mediaForm->setAction($this->url()); ?></div>
            <div class="span6">
                <?php if (!empty($this->image)) { ?>
                    <img src="<?php echo $this->serverUrl() . "/ads/" . $this->image; ?>" />
                <?php } ?>
                <?php if (!empty($this->banner)) { ?>
                    <img src="<?php echo $this->serverUrl() . "/ads/" . $this->banner; ?>" />
                <?php } ?>
            </div>
        </div>
    </div>
</div>
<script src="/js/createAdv.js"></script>