<?php $this->headScript()->appendFile($this->baseUrl("/js/select2/select2.min.js")) ?>
<?php $this->headScript()->appendFile($this->baseUrl("/js/select2/select2_locale_ru.js")) ?>
<?php $this->headScript()->appendFile("//maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places") ?>
<?php $this->headScript()->appendFile("//ubilabs.github.io/geocomplete/jquery.geocomplete.js") ?>
<?php $this->headScript()->appendFile($this->baseUrl("/js/jquery/jquery.maskedinput.min.js")) ?>
<?php $this->headScript()->appendFile($this->baseUrl("/js/ad.js")) ?>
<?php $this->headScript()->appendFile($this->baseUrl("/js/aciTree/jquery.aciPlugin.min.js")) ?>
<?php $this->headScript()->appendFile($this->baseUrl("/js/aciTree/jquery.aciTree.min.js")) ?>
<?php $this->headLink()->prependStylesheet($this->baseUrl("/css/aciTree.css")) ?>

<?php $this->headScript()->appendScript("
    $('#geo').aciTree({
        ajax: {
            url: '/geo/get-list'
        },
        selectable: true
    });
    $('#end_dt').on('changeDate', function(ev){
        $(this).datepicker('hide');
    });
    $('#public_dt').on('changeDate', function(ev){
        $(this).datepicker('hide');
    });
") ?>

<?php global $translate; ?>

<div id="view-content">
    <ul class="nav nav-tabs" id="ad">
        <li class="active"><a href="#main"><?php echo $translate->getAdapter()->translate("main"); ?></a></li>
        <li><a href="#dates"><?php echo $translate->getAdapter()->translate("dates"); ?></a></li>
        <li><a href="#settings"><?php echo $translate->getAdapter()->translate("settings"); ?></a></li>
        <li><a href="#contacts"><?php echo $translate->getAdapter()->translate("contacts"); ?></a></li>
        <li><a href="#media"><?php echo $translate->getAdapter()->translate("media"); ?></a></li>
        <li><a target="_blank" href="/ad/index/id/<?php echo $this->ad->id; ?>"><?php echo $translate->getAdapter()->translate("preview"); ?></a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="main"><?php echo $this->mainForm->setAction($this->url()); ?></div>
        <div class="tab-pane" id="dates"><?php echo $this->datesForm->setAction($this->url()); ?></div>
        <div class="tab-pane" id="settings">
            <div class="row">
                <div class="span5">
                    <?php echo $this->settingsForm->setAction($this->url()); ?>
                </div>
                <div class="span_regions">
                    <label><?= $translate->getAdapter()->translate("ad_region"); ?></label>
                    <div style="height: 320px; overflow-y: auto; border: 1px solid #cccccc; border-radius: 3px;">
                        <div id="geo_tree" class="aciTree"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane" id="contacts">
            <div class="row">
                <div class="span5">
                    <?php echo $this->contactsForm->setAction($this->url()); ?>
                </div>
                <div class="span5">
                    <ul class="zend form" style="list-style: none; margin-top: 14px; width: 530px;">
                        <li>
                            <label style="color:#999999;"><?= $translate->getAdapter()->translate("additional_addresses"); ?> *</label>
                        </li>
                        <li style="margin-left: -10px;">
                            <?php $this->additionalAddressAd($this->ad->addresses); ?>
                        </li>
</ul>
                    </div>

            </div>
        </div>
        <div class="tab-pane" id="media">
            <div class="span5"><?php echo $this->mediaForm->setAction($this->url()); ?></div>
            <div class="span6">
                <?php if (!empty($this->banner)) { ?>
                    <img src="<?php echo $this->serverUrl() . "/media/" . $this->banner; ?>" class="img-polaroid"/><br/><br/>
                <?php } ?>
                <?php if (!empty($this->image)) { ?>
                    <img id="banner" src="<?php echo $this->serverUrl() . "/media/" . $this->image; ?>" class="img-polaroid"/>
                <?php } ?>

            </div>
        </div>
    </div>
</div>

<?php if (!empty($this->gotoTab)) {?>
    <script type="text/javascript">
        <?php echo "window.location.hash = \"" . $this->gotoTab . "\";"; ?>
    </script>
<?php } ?>

<script>
    var bigBannerHelp = '&nbsp;<i class="icon-info-sign" id="big-banner-help" data-content="<?= $translate->getAdapter()->translate("image_info_text"); ?>" data-placement="top" data-toggle="popover" data-trigger="hover"></i>';
    var smallBannerHelp = '&nbsp;<i class="icon-info-sign" id="small-banner-help" data-content="<?= $translate->getAdapter()->translate("banner_info_text"); ?>" data-placement="top" data-toggle="popover" data-trigger="hover"></i>';
    var videoHelp = '&nbsp;<i class="icon-info-sign" id="video-help" data-content="<?= $translate->getAdapter()->translate("video_info_text"); ?>" data-placement="top" data-toggle="popover" data-trigger="hover"></i>';
</script>


<?php $this->headScript()->appendFile($this->baseUrl("/js/aciTree/jquery.aciPlugin.min.js")); ?>
<?php $this->headScript()->appendFile($this->baseUrl("/js/aciTree/jquery.aciTree.min.js")); ?>
<?php $this->headScript()->appendFile($this->baseUrl("/js/aciTree/jquery.aciTree.core.js")); ?>
<?php $this->headScript()->appendFile($this->baseUrl("/js/aciTree/jquery.aciTree.checkbox.js")); ?>
<?php $this->headScript()->appendFile($this->baseUrl("/js/aciTree/jquery.aciTree.utils.js")); ?>
<?php $this->headScript()->appendFile($this->baseUrl("/js/geo-tree.js")); ?>


