<?php global $translate; ?>
<?=$this->headMeta()->appendName('description', $translate->getAdapter()->translate("main_description"));?>
<?=$this->headTitle($this->ad->name);?>
<?=$this->headTitle()->setSeparator(' / ');?>
<div class="row">
    <div class="span6 details-left">
        <a href="#">
            <!-- /img/item2.jpg -->
            <?php if ($this->ad->video == "") { ?>
                <img width="auto" height="auto" src="/media/<?php echo $this->ad->image; ?>" class="img-polaroid">
            <?php } else { ?>
                <?php echo $this->ad->video; ?>
            <?php } ?>

        </a>

    </div>
    <div class="span6 details-right">
        <h4><?php echo $this->ad->name; ?></h4>
        <div><?php echo nl2br($this->ad->description); ?></div>
        <br><br>

        <div class="span5">
            <?php if ($this->ad->full_description) { ?>
                <a id="full-description" class="btn btn-info" href="#full-description-modal" data-id="<?php echo $this->ad->id; ?>">
                    <?php echo $translate->getAdapter()->translate("full_description"); ?>
                </a>
            <?php } ?>
            <div class="leftMargin muted"><?= $translate->getAdapter()->translate("days_left") . ": <strong>" . $this->ad->getDaysLeft() . "</strong>"?></div>
        </div>
        <div class="span5">

            <ul class="pager">
                <li class="previous <?= $this->prevAdUrl ? "" : "disabled" ?>">
                    <a href="<?= $this->prevAdUrl ?>">&larr; <?= $translate->getAdapter()->translate("prev_ad") ?></a>
                </li>
                <li>
                    <div id="favorites-link"
                         data-link="<?= $this->isFavorite ? $this->isFavoritesUrl : $this->notFavoritesUrl ?>"
                         title="<?= $this->isFavorite ? $translate->getAdapter()->translate("remove_from_favorites") : $translate->getAdapter()->translate("add_to_favorites") ?>"
                         data-id="<?= $this->ad->id ?>"
                         data-status="<?= $this->isFavorite ? "on" : "off" ?>"
                         class="favorites-icon <?= $this->isFavorite ? "favorites-icon-on" : "favorites-icon-off" ?>"></div>
                </li>
                <li class="next  <?= $this->nextAdUrl ? "" : "disabled" ?>">
                    <a href="<?= $this->nextAdUrl ?>"><?= $translate->getAdapter()->translate("next_ad") ?> &rarr;</a>
                </li>
            </ul>
        </div>
        <br><br><br>
        <div class="span5 top-offset">
            <strong><?= $translate->getAdapter()->translate("social_share")?></strong><br/>
            <script type="text/javascript">(function() {
                    if (window.pluso)if (typeof window.pluso.start == "function") return;
                    if (window.ifpluso==undefined) { window.ifpluso = 1;
                        var d = document, s = d.createElement('script'), g = 'getElementsByTagName';
                        s.type = 'text/javascript'; s.charset='UTF-8'; s.async = true;
                        s.src = ('https:' == window.location.protocol ? 'https' : 'http')  + '://share.pluso.ru/pluso-like.js';
                        var h=d[g]('body')[0];
                        h.appendChild(s);
                    }})();
            </script>
            <div class="pluso" data-background="transparent"
                 data-options="medium,square,line,horizontal,nocounter,theme=04" data-services="vkontakte,odnoklassniki,facebook,twitter,google,moimir,email"></div>


            <address>
                <a id="action-address" href="#">
                    <?php echo $this->ad->address; ?>
                </a>
                <p>
                <div>
                    <?php
                    foreach($this->ad->addresses->list as $addrItem) {
                        if ($addrItem["checked"]) {

                    echo'<a id="action-address" href="#">
                    '.$addrItem["name"].'</a><br/>';

                            //echo "<div>".$addrItem["name"]."</div>";
                        }
                    }
                    ?>
                </div>
                </p>
                <br>
                <div><span><?php echo $this->ad->phone; ?></span>
                    <?php if ($this->ad->phone1) { ?>
                        ,&nbsp;<span><?php echo $this->ad->phone1; ?></span>
                    <?php } ?>
                    <?php if ($this->ad->phone2) { ?>
                        ,&nbsp;<span><?php echo $this->ad->phone2; ?></span>
                    <?php } ?>
                </div>
                <a href="mailto:<?php echo $this->ad->email; ?>"><?php echo $this->ad->email; ?></a>
                <?php if ($this->ad->url) { ?>
                    <div><noindex><a href="<?php echo $this->ad->url; ?>" rel="nofollow" target="_blank"><?php echo $this->ad->url; ?></a></noindex></div>
                <?php } ?>
            </address>
        </div></div>


</div>
<div class="lock-gray"></div>
</div>

<div id="full-description-modal" class="modal hide" tabindex="-1">
    <div class="modal-header">
        <h3 id="myModalLabel"><?php echo $translate->getAdapter()->translate("full_description"); ?></h3>
    </div>
    <div class="modal-body">
        <p></p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal"><?php echo $translate->getAdapter()->translate("close"); ?></button>
    </div>
</div>

<div id="action-address-modal" class="modal hide" tabindex="-1">
    <div class="modal-header">
        <h3 id="myModalLabel"><?php echo $translate->getAdapter()->translate("map_position"); ?></h3>
    </div>
    <div class="modal-body">
        <input type="hidden" id="full-address" value="<?php echo $this->ad->address; ?>">
        <div class="map_canvas"></div>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal"><?php echo $translate->getAdapter()->translate("close"); ?></button>
    </div>
</div>


<script src="http://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places"></script>
<script type="text/javascript" src="/js/jquery/jquery.geocomplete.min.js"></script>
<script type="text/javascript" src="/js/full-action.js"></script>

