<?php global $translate; ?>
<div class="row">
    <div class="span6 details-left">
        <a href="#" class="img-wrapper">
            <!-- /img/item2.jpg -->
            <?php if ($this->ad->video == "") { ?>
                <img width="550" height="auto" src="/ads/<?php echo $this->ad->image; ?>" class="img-polaroid">
            <?php } else { ?>
                <div style="width:550px;"><?php echo $this->ad->video; ?></div>
            <?php } ?>
            <div class="img-info"><p><?php echo $this->ad->name; ?></p></div>
        </a>
        <br><br><br>
        <address>
            <strong><?php echo $this->user->enterprise; ?></strong>
            <?php echo $this->ad->address; ?>
            <br>
            <div><abbr title="Phone"><?php echo $translate->getAdapter()->translate("phone") ?>:</abbr> <?php echo $this->ad->phone; ?></div>
        <?php if ($this->ad->phone1) { ?>
            <div><abbr title="Phone"><?php echo $translate->getAdapter()->translate("phone") ?>:</abbr> <?php echo $this->ad->phone1; ?></div>
        <?php } ?>
        <?php if ($this->ad->phone2) { ?>
            <div><abbr title="Phone"><?php echo $translate->getAdapter()->translate("phone") ?>:</abbr> <?php echo $this->ad->phone2; ?></div>
        <?php } ?>
        </address>

        <address>
            <?php if ($this->ad->url) { ?>
                <div><a href="<?php echo $this->ad->url; ?>" target="_blank"><?php echo $this->ad->url; ?></a></div>
            <?php } ?>
            <a href="mailto:<?php echo $this->ad->email; ?>"><?php echo $this->ad->email; ?></a>
        </address>

    </div>
    <div class="span6 details-right">
        <h4><?php echo $this->ad->name; ?></h4>
        <div><?php echo $this->ad->description; ?></div>

        <br><br>
        <?php if ($this->ad->full_description) { ?>
            <a id="full-description" class="btn" href="#full-description-modal" data-id="<?php echo $this->ad->id; ?>">
                <?php echo $translate->getAdapter()->translate("full_description"); ?>
            </a>
        <?php } ?>

        

    </div>
</div>

<div id="full-description-modal" class="modal hide" tabindex="-1">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3 id="myModalLabel"><?php echo $translate->getAdapter()->translate("full_description"); ?></h3>
    </div>
    <div class="modal-body">
        <p>One fine body…</p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal">Close</button>
    </div>
</div>