<?php $this->headScript()->appendFile($this->baseUrl("/js/select2/select2.min.js")) ?>
<?php $this->headScript()->appendFile($this->baseUrl("/js/select2/select2_locale_ru.js")) ?>
<?php $this->headScript()->appendFile("//maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places") ?>
<?php $this->headScript()->appendFile("//ubilabs.github.io/geocomplete/jquery.geocomplete.js") ?>
<?php $this->headScript()->appendFile($this->baseUrl("/js/jquery/jquery.maskedinput.min.js")) ?>
<?php $this->headScript()->appendFile($this->baseUrl("/js/ad.js")) ?>
<?php $this->headScript()->appendScript("
    $('#end_dt').on('changeDate', function(ev){
        $(this).datepicker('hide');
    });
    $('#public_dt').on('changeDate', function(ev){
        $(this).datepicker('hide');
    });
") ?>

<?php global $translate; ?>
<div class="col-sm-12 col-lg-offset-2 col-lg-8">
    <ul class="nav nav-tabs" id="ad">
        <li class="active"><a href="#main"><?php echo $translate->getAdapter()->translate("main"); ?></a></li>
        <li><a href="#dates"><?php echo $translate->getAdapter()->translate("dates"); ?></a></li>
        <li><a href="#settings"><?php echo $translate->getAdapter()->translate("settings"); ?></a></li>
        <li><a href="#contacts"><?php echo $translate->getAdapter()->translate("contacts"); ?></a></li>
        <li><a href="#media"><?php echo $translate->getAdapter()->translate("media"); ?></a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="main"><?php echo $this->mainForm->setAction($this->url()); ?></div>
        <div class="tab-pane" id="dates"><div class="col-xs-12 col-sm-3"><?php echo $this->datesForm->setAction($this->url()); ?></div></div>
        <div class="tab-pane" id="settings"><div class="col-xs-12 col-sm-6"><?php echo $this->settingsForm->setAction($this->url()); ?></div></div>
        <div class="tab-pane" id="contacts"><div class="col-xs-12 col-sm-6"><?php echo $this->contactsForm->setAction($this->url()); ?></div></div>
        <div class="tab-pane" id="media">
            <div class="row-fluid">
                <div class="col-xs-12 col-sm-6"><?php echo $this->mediaForm->setAction($this->url()); ?></div>
                <div class="col-xs-12 col-sm-6">
                    <?php if (!empty($this->image)) { ?>
                        <img src="/media/<?php echo $this->image; ?>" class="img-polaroid"/><br/><br/>
                    <?php } ?>
                    <?php if (!empty($this->banner)) { ?>
                        <img id="banner" src="/media/<?php echo $this->banner; ?>" class="img-polaroid"/>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php if (!empty($this->gotoTab)) {?>
    <script type="text/javascript">
        <?php echo "window.location.hash = \"" . $this->gotoTab . "\";"; ?>
    </script>
<?php } ?>


<script>
    var smallBannerHelp = '&nbsp;<i class="icon-info-sign" id="small-banner-help" data-content="<?= $translate->getAdapter()->translate("banner_info_text"); ?>" data-placement="top" data-toggle="popover" data-trigger="hover"></i>';
    var bigBannerHelp = '&nbsp;<i class="icon-info-sign" id="big-banner-help" data-content="<?= $translate->getAdapter()->translate("image_info_text"); ?>" data-placement="top" data-toggle="popover" data-trigger="hover"></i>';
    var videoHelp = '&nbsp;<i class="icon-info-sign" id="video-help" data-content="<?= $translate->getAdapter()->translate("video_info_text"); ?>" data-placement="top" data-toggle="popover" data-trigger="hover"></i>';
</script>


