

<div class="col-sm-12 col-md-12 col-lg-10 col-lg-offset-1 landing-wrapper">
<div class="title-block">
    <h2 id="details-block" class="text-center">Детальніше про SaleOn</h2>
</div>

<div class="jumbotron details-block block row" style="background: rgb(226,234,239);">
    <div class="col-sm-offset-2 col-sm-8">
        <ul class="media-list">
            <li class="media">
                <div class="media-left">
                    <i class="fa fa-fighter-jet"></i>
                </div>
                <div class="media-body">
                    Перший, унікальний, ресурс споживачів акцій і знижок з підпискою на бренд
                </div>
            </li>

            <li class="media">
                <div class="media-left">
                    <i class="fa fa-ban"></i>
                </div>
                <div class="media-body">
                    Ніякого спаму та реклами, ми піклуємося про Ваших кліентів
                </div>
            </li>

            <li class="media">
                <div class="media-left">
                    <i class="fa fa-magnet"></i>
                </div>
                <div class="media-body">
                    Системне залучення та інформування підписників на акції та знижки Вашого бренду
                </div>
            </li>

            <li class="media">
                <div class="media-left">
                    <i class="fa fa-share-alt"></i>
                </div>
                <div class="media-body">
                    Безкоштовне просування Ваших акцій і знижок в наших соціальних мережах
                </div>
            </li>

            <li class="media">
                <div class="media-left">
                    <i class="fa fa-users"></i>
                </div>
                <div class="media-body">
                    Збільшення споживання Ваших акцій і знижок в рази за рахунок інформування аудиторії Ваших цільових
                    підписників
                </div>
            </li>
        </ul>
    </div>
</div>

<div class="video-block block row">
    <div class="col-xs-12 col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6">
        <div align="center" class="embed-responsive embed-responsive-16by9">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/6uYn-EVlCI8" frameborder="0" allowfullscreen></iframe>
        </div>
    </div>
</div>

<div class="more-details-block block row" style="background: rgb(226,234,239);">
    <div>
        <h2 class="text-center">Чим корисний SaleOn Вашій компанії?</h2>
    </div>

    <p class="row">

    <div class="col-sm-offset-2 col-sm-8">
        <ul class="media-list">
            <li class="media">
                <div class="media-left">
                    <i class="fa fa-envelope-o"></i>
                </div>
                <div class="media-body">
                    Моментальне інформування Ваших підписників про нові акції і знижки
                </div>
            </li>
            <li class="media">
                <div class="media-left">
                    <i class="fa fa-plus-square-o"></i>
                </div>
                <div class="media-body">
                    Необмежена можливість додавати акції та знижки в будь-який час доби
                </div>
            </li>
            <li class="media">
                <div class="media-left">
                    <i class="fa fa-cogs"></i>
                </div>
                <div class="media-body">
                    Технічна підтримка для представників бренду і контроль за розміщеним контентом
                </div>
            </li>
            <li class="media">
                <div class="media-left">
                    <i class="fa fa-facebook-square"></i>
                </div>
                <div class="media-body">
                    Безкоштовне просування в наших соціальних мережах
                </div>
            </li>
            <li class="media">
                <div class="media-left">
                    <i class="fa fa-wrench"></i>
                </div>
                <div class="media-body">
                    Зручний функціонал, який допоможе розмістити акції та знижки всього за декілька кліків
                </div>
            </li>
            <li class="media">
                <div class="media-left">
                    <i class="fa fa-smile-o"></i>
                </div>
                <div class="media-body">
                    І все це АБСОЛЮТНО БЕЗКОШТОВНО!
                </div>
            </li>
        </ul>
    </div>
    </p>

    <p class="text-center">
        <a href="/partner/profile"><button class="btn btn-lg btn-success">Спробувати просто зараз</button></a>
    </p>
</div>

<div class="not-coupon-block block row">
    <h2 class="text-center">Чим ми відрізняємося від купонників?</h2>

    <div class="row">
        <div class="col-xs-12 col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6 ">
            <img style="width: 100%;" src="/static/img/cupons.png"/>
        </div>
    </div>
    <br/>

    <div class="row">
        <div class="col-sm-offset-2 col-sm-8">
            <ul class="media-list">
                <li class="media">
                    <div class="media-left">
                        <i class="fa">1</i>
                    </div>
                    <div class="media-body">
                        Ми знаходимо Вашу постійну цільову аудиторію споживачів акцій і знижок
                    </div>
                </li>
                <li class="media">
                    <div class="media-left">
                        <i class="fa">2</i>
                    </div>
                    <div class="media-body">
                        Ми будемо системно поповнювати Вашу гарячу аудиторію підписників
                    </div>
                </li>
                <li class="media">
                    <div class="media-left">
                        <i class="fa">3</i>
                    </div>
                    <div class="media-body">
                        Вам не потрібно витрачати багато часу для взаємодій з нами
                    </div>
                </li>
                <li class="media">
                    <div class="media-left">
                        <i class="fa">4</i>
                    </div>
                    <div class="media-body">
                        Ми можемо додатково інформувати Ваших підписників про інші важливі події в житті Вашої компанії

                    </div>
                </li>
                <li class="media">
                    <div class="media-left">
                        <i class="fa">5</i>
                    </div>
                    <div class="media-body">
                        Ми робимо для Вас це АБСОЛЮТНО БЕЗКОШТОВНО!
                    </div>
                </li>
            </ul>
        </div>
    </div>

    <p class="text-center">
        <a href="/partner/profile"><button class="btn btn-lg btn-success">Зареєструвати Ваш бренд</button></a>
    </p>
</div>

<div class="please-connect-block block row" style="background: rgb(226,234,239);">
    <h2 class="text-center">Приєднуйтесь до успіху вже сьогодні!</h2>
    <br/>

    <p class="text-center">
        <a href="/partner/profile"><button class="btn btn-lg btn-success">Додати акцію або знижку</button></a>
    </p>
</div>

<div class="please-connect-block block row">
    <h2 class="text-center">Залишились питання?</h2>

    <h3 class="text-center">
        Залиште свої контакти<br/>
        і ми негайно <strong>зв'яжемося з Вами</strong>!
    </h3>
    <br/>

    <p class="text-center">
        <button class="btn btn-lg btn-danger">
            Зв'язатися з нами
        </button>
    </p>
</div>


</div>

<?php $this->headLink()->appendStylesheet('/css/profile-lending.css'); ?>
<?php $this->headScript()->appendFile("/js/partner-lending.js")?>