<?php global $translate; ?>

<div class="row">
    <div class="span6">
        <div class="legend"><?php echo $translate->getAdapter()->translate("enter"); ?></div>
        <?php echo $this->loginForm->setAction($this->url(array('controller'=>'auth', 'action'=>'index'))); ?>
        <div id="contact_button">

            <input type="button" value="<?= $translate->getAdapter()->translate("contacts") ?>"
                   onclick="window.location='/index/contacts';" />
            </div>
    </div>
    <div class="span6">
        <div class="legend"><?php echo $translate->getAdapter()->translate("new_partner_reg"); ?>
        </div>
        <?php echo $this->registrationForm->setAction($this->url()); ?>
    </div>
</div>