<?php global $translate; ?>
<br />
<div id="view-content">
    <div class="row">
        <div class="span6">
            <legend><?php echo $translate->getAdapter()->translate("set_new_password"); ?></legend>
            <?php echo $this->changePasswordForm->setAction($this->url()); ?>
            <div class="legend"><?php echo $translate->getAdapter()->translate("info"); ?></div>
            <p><?php echo $this->email; ?></p>
        </div>

        <div class="span6">
            <div class="legend"><?php echo $translate->getAdapter()->translate("profile"); ?></div>
            <?php echo $this->form->setAction($this->url()); ?>
        </div>
    </div>
</div>