<?php global $translate; ?>
<br />
<div id="view-content">
    <div class="row">
        <div class="span6">
            <div class="legend"><?php echo $translate->getAdapter()->translate("set_new_password"); ?></div>
            <?php echo $this->changePasswordForm->setAction($this->url()); ?>
            <div class="legend"><?php echo $translate->getAdapter()->translate("info"); ?></div>
            <p><?php echo $this->email; ?></p>
        </div>

        <div class="span6">
            <div class="legend"><?php echo $translate->getAdapter()->translate("profile"); ?></div>
            <?php echo $this->form->setAction($this->url()); ?>
        </div>
    </div>
</div>

<script src="http://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places"></script>
<script type="text/javascript" src="/js/jquery.geocomplete.min.js"></script>
<script type="text/javascript" src="/js/jquery.maskedinput.min.js"></script>
<script type="text/javascript">
    $(function () {
        $("#phone").add("#phone1").add("#phone2").mask("(999) 999-9999");
        $("#address").geocomplete();
    });
</script>
