<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Waw site</title>
    <?php
    global $translate;
    echo $this->jQuery()
        ->setVersion('1.9.1')
        ->setUiVersion('1.10.3')
        ->enable()
        ->uiEnable();
    ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <?php $this->headLink()->prependStylesheet($this->baseUrl('css/style.css')); ?>
    <?php $this->headLink()->prependStylesheet($this->baseUrl('css/select2.css')); ?>
    <?php $this->headLink()->prependStylesheet($this->baseUrl('css/datepicker.css')); ?>
    <?php $this->headLink()->prependStylesheet($this->baseUrl('css/redmond/jquery-ui-1.10.3.custom.min.css')); ?>
    <?php $this->headLink()->prependStylesheet($this->baseUrl('css/bootstrap-responsive.css')); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl('css/bootstrap.css')); ?>
    
</head>
<body>
<div class="topbg"></div>

<div id="wrap">
    <div class="container">
            <div class="row">
                <div class="top-menu">
                <div class="span4">
                    <button id="btn1" title="Регионы" class="btn btn-large" type="button"><i class="myicon-region"></i></button>
                    <button id="btn2" title="Категории" class="btn btn-large" type="button"><i class="myicon-category"></i></button>
                    <button id="btn3" title="Бренды" class="btn btn-large" type="button"><i class="myicon-brands"></i></button>
                </div>
                <div class="span3 jumbotron">
                    <a href="/"><div class="logo"></div></a>
                </div>
                <div class="span4">
                    <a href="#" id="btn4" title="Новое" class="btn btn-large" type="button"><i class="myicon-new"></i></a>
                    <?php
                        $auth = Zend_Auth::getInstance();
                        if ($auth->hasIdentity()) { ?>
                            <?php if ($auth->getIdentity()->role == "PARTNER") { ?>
                                <a href="/partner/profile" title="Партнерам" class="btn btn-large" type="button"><i class="myicon-partners"></i></a>
                                <a href="/auth/logout" title="Выйти" class="btn btn-large" type="button"><i class="myicon-logout"></i></a>
                            <?php } else { ?>
                                <button id="btn5" title="Избранное" class="btn btn-large" type="button"><i class="myicon-favorites"></i></button>
                                <a href="/auth/logout" title="Выйти" class="btn btn-large" type="button"><i class="myicon-logout"></i></a>
                            <?php } ?>
                        <?php } else { ?>
                            <a href="/user/new" id="btn4" title="Пользователь" class="btn btn-large" type="button"><i class="myicon-partners"></i></a>
                            <a href="/partner/profile" title="Партнерам" class="btn btn-large" type="button"><i class="myicon-partners"></i></a>
                        <?php }
                    ?>
                </div>
                </div>
            </div>
        <?php echo $this->navigationBar($this->link); ?>
        <div class="layout-content">
            <?php echo $this->layout()->content; ?>
        </div>
    </div>
    <div id="push"></div>
</div>

<div id="success-modal-block" class="footer-message alert-success hide">
    <p class="block-label text-center"><?php echo $this->successMessage; ?></p>
</div>

<div id="error-modal-block" class="footer-message alert-error hide">
    <p class="block-label text-center"><?php echo $this->errorMessage; ?></p>
</div>

<div id="footer" class="footer footer-gradient">
    <div class="container">
        <p class="credit">ВАУ - Все акции Украины, 2013 </p>
        <div id="footer-social" class="socials"></div>
    </div>
</div>



<script src="/js/bootstrap-modal.js"></script>
<script src="/js/bootstrap-dropdown.js"></script>
<script src="/js/bootstrap-tab.js"></script>
<script src="/js/bootstrap-tooltip.js"></script>
<script src="/js/bootstrap-button.js"></script>
<script src="/js/bootstrap-popover.js"></script>
<script src="/js/bootstrap-datepicker.js"></script>
<script src="/js/common.js"></script>

</body>
</html>
