<?php global $translate; ?>

<div class="row">
    <div class="span6">
        <div class="legend"><?php echo $translate->getAdapter()->translate("enter"); ?></div>
        <?php echo $this->loginForm->setAction($this->url(array('controller'=>'auth', 'action'=>'index'))); ?>
        <div id="contact_button">

            <a href="/index/contacts"><?= $translate->getAdapter()->translate("contacts") ?></a><br/>
        </div>
        <div id="auth_through">
        <div class="legend"><?php echo $translate->getAdapter()->translate("enter_throw"); ?>
        </div>
<!--        <div><a href="//= $this->googleLink;">Google+</a></div>-->
        <div id="socials"><a href="/auth/auth/by/facebook" target="_blank"><div class="fb"></div></a>
        <a href="/auth/auth/by/twitter" target="_blank"><div class="twitter"></div></a>
        <a href="/auth/auth/by/vkontakte" target="_blank"><div class="vk"></div></a></div>
    </div>
    </div>
    <div class="span6">
        <div class="legend"><?php echo $translate->getAdapter()->translate("new_user_reg"); ?></div>
        <?php echo $this->registrationForm->setAction($this->url()); ?>
    </div>
</div>