<?php global $translate; ?>

<div class="row">
    <div class="span6">
        <div class="legend"><?php echo $translate->getAdapter()->translate("enter"); ?></div>
        <?php echo $this->loginForm->setAction($this->url(array('controller'=>'auth', 'action'=>'index'))); ?>
        <div class="legend"><?php echo $translate->getAdapter()->translate("enter_throw"); ?>
      <button id="contact-btn" title="<?= $translate->getAdapter()->translate("contacts")?>" class="btn dropdown-toggle contacts"></button>
        </div>
<!--        <div><a href="//= $this->googleLink;">Google+</a></div>-->
        <div><a href="/auth/auth/by/facebook" target="_blank">Facebook</a></div>
        <div><a href="/auth/auth/by/twitter" target="_blank">Twitter</a></div>
        <div><a href="/auth/auth/by/vkontakte" target="_blank">VKontakte</a></div>
    </div>
    <div class="span6">
        <div class="legend"><?php echo $translate->getAdapter()->translate("new_user_reg"); ?></div>
        <?php echo $this->registrationForm->setAction($this->url()); ?>
    </div>
</div>