<?php global $translate; ?>
<?php $this->headTitle($translate->getAdapter()->translate("password_recovery")); ?>
<br/>
<div class="col-xs-12 col-sm-offset-2 col-sm-8">
<?php if ($this->successMsg) { ?>
    <div class="alert alert-success"><?php echo $this->successMsg; ?></div>
<?php } else { ?>
<div class="form-horizontal well">
    <h2 class="legend"><?php echo $translate->getAdapter()->translate("password_recovery"); ?></h2>
    <?php echo $this->form->setAction($this->url()); ?>
    <?php if ($this->errorMsg) { ?>
        <div class="alert alert-danger"><?php echo $this->errorMsg; ?></div>
    <?php } ?>
</div>
<?php } ?>
</div>
