<div>
    <div class="span4">
        <div style="height: 450px; overflow-y: auto; border: 1px solid #cccccc; border-radius: 3px;">
            <div id="geo_tree" class="aciTree"></div>
        </div>
    </div>
    <div class="span6">
        <div id="info">
            <?= $this->geoEditForm->setAction('/geo/add'); ?>
        </div>
    </div>
</div>

<script type="text/javascript" src="/js/jquery/jquery.geocomplete.min.js"></script>
<script type="text/javascript" src="/js/jquery/jquery.maskedinput.min.js"></script>

<link rel="stylesheet" type="text/css" href="/css/aciTree.css" media="all">
<link rel="stylesheet" type="text/css" href="/css/jquery.contextMenu.css" media="all">
<script type="text/javascript" src="/js/aciTree/jquery.aciPlugin.min.js"></script>
<script type="text/javascript" src="/js/aciTree/jquery.aciTree.min.js"></script>
<script type="text/javascript" src="/js/aciTree/jquery.contextMenu.js"></script>
<script type="text/javascript" src="/js/aciTree/jquery.aciSortable.min.js"></script>
<script type="text/javascript" src="/js/geoEditor.js"></script>